DarkMode for user profile has been done
warmachine028/memories pull request #110
Opened 2023-10-06 20:53 UTC by waleedkhano

# Issue #109 📐

- I worked on feature #109

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

## Issue to be closed 🛅

- My pull request closes #109

## Screenshots 📷

Here are the video of changes that I have made 🔽

https://github.com/warmachine028/memories/assets/110036553/6bad3cf4-f549-4dcf-93db-7baabedbd308

2023-10-06 22:12 UTC, warmachine028 commented
Pretty quick, quite impressive work. I'll review it

2023-10-06 22:15 UTC, warmachine028 requested changes
Instead of doing it in inline styles, could you please work on the classes.component comming from styles.js? 
The inline styles surely get the job done but it clutters the code for developer's

2023-10-07 06:02 UTC, waleedkhano commented
Sure

2023-10-07 06:40 UTC, waleedkhano commented
@warmachine028 please review the code in which I replaced the inline styles with classes.

2023-10-07 16:41 UTC, warmachine028 requested changes
- ![image](https://github.com/warmachine028/memories/assets/75939390/909f1acf-4b41-4d98-891c-17d92d7944f3)

These texts must not appear white in Light mode, the original color was alright.

- ![image](https://github.com/warmachine028/memories/assets/75939390/212d6760-b3e4-4b84-b1da-f090e1dfc347)
These card texts are not properly visible in dark mode, please fix them too

- ![image](https://github.com/warmachine028/memories/assets/75939390/5c4abd22-8265-4990-9005-28d5a7f22b86)

the title of these posts in commnents would look better in white for only dark mode.

2023-10-07 18:45 UTC, waleedkhano commented
Could you please specify the location of the comments and the card?

it looks ok here
![card](https://github.com/warmachine028/memories/assets/110036553/2eb540be-cb10-4029-8138-ceedd66934fa)


 
![comments](https://github.com/warmachine028/memories/assets/110036553/778c4dab-a152-4492-a3f6-57d847600a40)

2023-10-08 02:42 UTC, warmachine028 commented
https://github.com/warmachine028/memories/tree/main/client/src/components/PostDetails/CommentSection

https://github.com/warmachine028/memories/tree/main/client/src/components/PostDetails/CommentSection

2023-10-08 09:01 UTC, waleedkhano commented
card text has been changed to white

![1](https://github.com/warmachine028/memories/assets/110036553/3120408d-b4e9-4e44-bc17-dcffb44f8e73)

comment title text also changed 

![2](https://github.com/warmachine028/memories/assets/110036553/0ceb61e1-0d7c-41e7-af3d-36daf3de284b)

2023-10-08 09:30 UTC, warmachine028 requested changes
Build failed, please see the Logs

![Screenshot_2023-10-08-14-59-14-526_com android chrome](https://github.com/warmachine028/memories/assets/75939390/5eded23b-6327-4e16-9520-85ec67e4d3a2)

2023-10-08 09:34 UTC, warmachine028 approved these changes

2023-10-08 09:34 UTC, warmachine028 commented on client/src/components/User/Details/index.jsx
Why did you delete this file? Was it by accident?

2023-10-08 16:04 UTC, warmachine028 requested changes
![Screenshot_2023-10-08-21-32-37-742_com android chrome](https://github.com/warmachine028/memories/assets/75939390/451208f5-2430-4925-87c3-ff479702a21f)

- Can you add a thin border of greyish color in the dark mode only to these cards, they are very difficult to distinguish in the dark mode.

- Also please merge the latest changes to resolve the merge conflict occuring in the file.

2023-10-08 16:44 UTC, waleedkhano commented
Added border to card

![Screenshot 2023-10-08 213849](https://github.com/warmachine028/memories/assets/110036553/2fd79b71-8dec-40d9-a725-983f7d87923f)

2023-10-08 16:48 UTC, warmachine028 commented
Also resolve the conflicts too

2023-10-08 16:52 UTC, warmachine028 approved these changes
Changes Look good. 
If you resolve the merge conflicts, I'll merge it to main right away

2023-10-08 18:19 UTC, warmachine028 commented
No worries I have resolved the merge conflict. Happy hacktoberfest 🎉

2023-10-08 18:24 UTC, merged