hacktoberfest banner replacement
warmachine028/memories pull request #122
Opened 2023-10-15 18:27 UTC by adisuyash

I have replaced the Hacktoberfest banner & did some necessary documentation changes which will provide a better user experience.

 [AdiSuyash](github.com/adisuyash) have worked for #121 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #121 

## Screenshots 📷
<img width="493" alt="image" src="https://github.com/warmachine028/memories/assets/116362593/a8ed0108-077b-451e-9a82-6ccdc55152c6">

Here are the pictures of changes that I have made 🔽

<attach screenshots here>
  
  
  
---

2023-10-15 18:41 UTC, warmachine028 requested changes
![Screenshot_2023-10-16-00-10-03-940_com android chrome](https://github.com/warmachine028/memories/assets/75939390/7e61d740-73d2-4099-a0bd-8a2ae1630534)
Missing center alignment

2023-10-15 18:41 UTC, warmachine028 commented on README.md
> +- [Memories](#memories)
Restore this section

2023-10-15 18:42 UTC, warmachine028 commented
See closed PRs and correct the top portion of the PR template

2023-10-15 21:28 UTC, warmachine028 commented
Make the changes first please

2023-10-16 06:34 UTC, adisuyash commented
I have mistakenly committed these changes.
Please check again & share the feedback

2023-10-16 06:39 UTC, adisuyash commented
> Make the changes first please

I have corrected the PR

2023-10-16 16:46 UTC, warmachine028 commented
Please center align the items

2023-10-17 05:15 UTC, warmachine028 approved these changes
I have made the necessary changes

2023-10-17 05:17 UTC, merged