Avinasdube toggle button
warmachine028/memories pull request #51
Opened 2023-07-12 17:34 UTC by avinasdube

# Issue  📐

- I Avinash Dubey (@avinasdube) have worked for #43

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] Contribution Guidelines
- [x] Code of Conduct

## Issue to be closed 🛅

- My pull request closes #43 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

In Light Mode :
  
![LightMode](https://github.com/warmachine028/memories/assets/85872996/581baea2-822b-4c45-99a6-6fbce87b2c71)

In Dark Mode :

---
![DarkMode](https://github.com/warmachine028/memories/assets/85872996/bfd13990-5456-46f6-9854-58037647649f)

2023-07-12 18:28 UTC, warmachine028 requested changes

2023-07-12 18:28 UTC, warmachine028 commented on server/.env.example
This was an just an example file to set up `.env.local`, its contents are for demonstration only. It needs to be reverted back to original.

2023-07-13 09:57 UTC, avinasdube commented
I have fixed all the suggestion you requested. I hope everything is up, running and good now.

2023-07-13 15:07 UTC, warmachine028 commented
Great work! I would be reviewing this PR shortly.

2023-07-15 06:02 UTC, avinasdube commented
> Great work! I would be reviewing this PR shortly.

Hey, What happened ? Still not reviewed !

2023-07-15 06:24 UTC, warmachine028 approved these changes

2023-07-15 06:24 UTC, merged

2023-07-15 07:22 UTC, avinasdube commented
Thank You for giving me opportunity to make my little contribution in your project. 🙏🏻

2023-07-15 07:42 UTC, warmachine028 commented
Keep progressing like this 🚀. Wishing you for more such moments !